from datetime import datetime


SEVERITY_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🟢"
}


def compute_structural_grade(warnings, walls, rooms):
    """
    Compute an overall structural safety grade (A–F).
    Based on: warning severity counts, wall coverage, room spans.
    """
    penalty = 0
    for w in warnings:
        sev = w.get("severity", "low")
        penalty += {"critical": 25, "high": 15, "medium": 8, "low": 3}.get(sev, 0)

    score = max(0, 100 - penalty)
    grade = (
        "A+" if score >= 92 else
        "A"  if score >= 85 else
        "B"  if score >= 75 else
        "C"  if score >= 60 else
        "D"  if score >= 45 else
        "F"
    )
    return score, grade


def generate_report(walls, rooms, load_bearing, recommendations, cost_estimation, warnings):
    """
    Comprehensive structural engineering report with:
    - Executive summary
    - Structural grade
    - Room analysis
    - Material breakdown
    - Cost summary
    - Prioritized warnings
    - Recommendations
    """
    score, grade = compute_structural_grade(warnings, walls, rooms)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Wall statistics
    lb_count = len(load_bearing)
    pt_count = len(walls) - lb_count
    total_wall_len_m = sum(w["length"] * 0.025 for w in walls)
    avg_score = (
        sum(w.get("structural_score", 50) for w in walls) / len(walls)
        if walls else 0
    )

    # Room statistics
    room_summary = []
    for r in rooms[:8]:  # top 8 rooms
        room_summary.append({
            "label": r.get("label", "Room"),
            "area_sqm": r.get("area_sqm", 0),
            "span_m": round(max(r["width"], r["height"]) * 0.025, 1),
            "aspect_ratio": r.get("aspect_ratio", 1.0)
        })

    # Material summary
    material_counts = {}
    for rec in recommendations:
        mat = rec["primary_material"]
        material_counts[mat] = material_counts.get(mat, 0) + 1

    # Warning summary
    warning_summary = {
        "critical": sum(1 for w in warnings if w.get("severity") == "critical"),
        "high": sum(1 for w in warnings if w.get("severity") == "high"),
        "medium": sum(1 for w in warnings if w.get("severity") == "medium"),
        "low": sum(1 for w in warnings if w.get("severity") == "low"),
        "total": len(warnings)
    }

    # Key recommendations (top 5)
    key_actions = []
    for w in warnings[:5]:
        if w.get("recommendation"):
            key_actions.append({
                "severity": w["severity"],
                "action": w["recommendation"],
                "icon": SEVERITY_EMOJI.get(w["severity"], "⚪")
            })

    return {
        "metadata": {
            "generated_at": timestamp,
            "system": "Autonomous Structural Intelligence System v2.0",
            "version": "2.0.0"
        },
        "structural_grade": {
            "score": score,
            "grade": grade,
            "interpretation": (
                "Structurally sound — minor optimizations possible." if score >= 75 else
                "Moderate structural concerns — engineering review recommended." if score >= 50 else
                "Significant structural issues — immediate professional review required."
            )
        },
        "summary": {
            "total_walls": len(walls),
            "load_bearing_walls": lb_count,
            "partition_walls": pt_count,
            "total_rooms": len(rooms),
            "total_wall_length_m": round(total_wall_len_m, 1),
            "avg_structural_score": round(avg_score, 1),
            "lb_ratio_pct": round(lb_count / max(len(walls), 1) * 100, 1)
        },
        "rooms": room_summary,
        "materials": {
            "breakdown": material_counts,
            "recommendations_count": len(recommendations)
        },
        "cost": {
            "total_construction_cost": cost_estimation.get("total_cost", 0),
            "total_with_finishing": cost_estimation.get("total_with_finishing", 0),
            "material_cost": cost_estimation.get("breakdown", {}).get("material_cost", 0),
            "labor_cost": cost_estimation.get("breakdown", {}).get("labor_cost", 0),
            "currency": "INR"
        },
        "warnings": warnings,
        "warning_summary": warning_summary,
        "key_actions": key_actions,
        "professional_note": (
            "This report is generated by an AI vision system and is intended for "
            "preliminary assessment only. All structural decisions must be validated "
            "by a licensed structural engineer before construction."
        )
    }
